### ISSUE TITLE
Intro

### ISSUE THREAD

**Issue by josephfusco** [pikappaphi/discussion#1]
# Welcome!

@pikappaphi/general 

Hey guys this should be super relaxed. I just thought it would be a neat way for us to help the chapter, philanthropy and just work on some neat project together. If you know of other brothers on GitHub, you are all admins in the general team and should be able to invite them. Remember if you want to display the group publicly on your profile, [here is how to it](https://help.github.com/articles/publicizing-or-hiding-organization-membership/).

If you are new to GitHub, no worries! We all were at one point.

## Goal

Collaborate through code and give back to the fraternity & philanthropy. If you have an idea, [tell us](https://github.com/pikappaphi/discussion/issues/new)!

## Resources 

Git can be kind of scary sometimes. Here are some great resources to getting started.

+ [Got 15 minutes and want to learn Git?](https://try.github.io/levels/1/challenges/1)

**Comment by brettjurgens** [comment]
@josephfusco thanks for getting this all set up. I had emailed Nationals like 2 years ago about setting up a common CMS/infrastructure and was met with a negative response. Glad to see things have changed.

**Comment by josephfusco** [comment]
@brettjurgens too bad. I saw you had your chapters website setup with Sinatra when i did a search for pi kappa phi. pretty cool! I thought it would be cool to eventually get some themes up here, wether they are for WordPress  or even just Jekyll using GitHub pages. Just as resources for brothers. 

Unfortunately national as a whole is not too techy from my understanding, and its hard to see value in things if only a few people request it. A global CMS setup would cost a substantial amount of money, and I don't think they have any in house developers to assign to a task like that. That's why I created this GitHub org. :smile: But I know for a fact we have some brothers that do mess around with this for fun and hopefully we can get some awesome resources created for chapters out there in the wild.

**Comment by brettjurgens** [comment]
in case you're interested:

![screen shot 2015-09-04 at 11 39 28 am](https://cloud.githubusercontent.com/assets/1226910/9690856/892daa6a-5304-11e5-933b-19135936ff7e.png)
![screen shot 2015-09-04 at 11 39 46 am](https://cloud.githubusercontent.com/assets/1226910/9690857/8b18eb1e-5304-11e5-814b-3835948bb556.png)
![screen shot 2015-09-04 at 11 39 59 am](https://cloud.githubusercontent.com/assets/1226910/9690860/8d6d4dc4-5304-11e5-844f-bf14056a6192.png)

**Comment by brettjurgens** [comment]
anyway, our setup is definitely pretty hacky and I think setting something more official up would be a great idea. if anyone else is interested, i think we should discuss stack and priorities

**Comment by josephfusco** [comment]
I am definitely interested in helping out with something like this. This is a great first project I believe and one of the biggest that chapters faces. I am setting us up a slack team to discuss it further.

**Comment by ReidHartman** [comment]
A+ teamwork everyone
